# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  push_to_other_repo:
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Create folder and file
      id: folder
      run: |
       mkdir "Test"
       echo "Hello World" >> Test/hello.txt
       cd Test
       set currentDir = %cd%
       echo '::set-output name=folderPath::{currentDir}' 
    -
      name: Checkout repository
      uses: actions/checkout@v2
      with:
          fetch-depth: 0  
    - 
      name: Pushes to another repository
      run: |
          bash .github/workflows/scripts/entrypoint.sh "${{steps.folder.outputs.folderPath}}"
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}


    
