# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  create_files:
    runs-on: windows-latest
    outputs:
      specs_artifactory: ${{ steps.spec_dir.outputs.name }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: checkout current repo
      uses: actions/checkout@v3
      
    - run: |
       cmd %cd%
      
    - name: Create folder and file
      id: spec_dir
      run: |
       echo  ${{github.ref_name }}
       mkdir ${{github.ref_name }}
       echo "Hello World" >> ${{github.ref_name }}/hello.txt
       echo "Hello World" >> ${{github.ref_name }}/hello2.txt
       echo "::set-output name=name::${{github.ref_name }}"
       
    - run: |
       cmd %cd%
      
    -   name: Upload spec files
        uses: actions/upload-artifact@v2
        with:
          name: ${{github.ref_name}}
          path: ${{github.ref_name}}
          
     
      
  push_to_other_repo:
    runs-on: windows-latest
    needs: create_files
    outputs: 
     source: steps.download.outputs.download-path
    steps:
    
    - name: checkout destination repo
      uses: actions/checkout@v3
      with:
       repository: divyajuluri/Automation
       fetch-depth: 0
    - 
     name: Download specs files
     id: download
     uses: actions/download-artifact@v2
     with:
       name: ${{needs.create_files.outputs.specs_artifactory}} 
       
    -
      run: | 
       cp ${{format('{0}/hello.txt', steps.download.outputs.download-path}} target
       git add -A
       git status
       

